services:
  frontend:
    image: ghcr.io/cobyl/mdd2-dataset-frontend:latest
    container_name: mdd2-dataset-frontend
    restart: unless-stopped
    networks:
      - app-network

  backend:
    image: ghcr.io/cobyl/mdd2-dataset-backend:latest
    container_name: mdd2-dataset-backend
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - app-network
      - db-network
    depends_on:
      - database

  database:
    image: postgres:18-alpine
    container_name: mdd2-dataset-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-app_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME:-app_database}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - db-network

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOZZLE_PASSWORD_HASH=${DOZZLE_PASSWORD_HASH}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy_data:/data
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - app-network

  watchtower:
    image: nickfedor/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REPO_USER=${GHCR_USERNAME}
      - REPO_PASS=${GHCR_PAT}
      - WATCHTOWER_POLL_INTERVAL=60
      - WATCHTOWER_CLEANUP=true

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOZZLE_BASE=/logs/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  db-network:
    driver: bridge

volumes:
  pgdata: